squirrelfanbase/board/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create_post, name='create_post'),
    path('<id>/', views.detail_view_post, name='detail_view_post'),
    path('<id>/update', views.update_view_post, name='update_view_post'),
    path('<id>/delete', views.delete_post, name='delete_post'),
    path('<post_id>/<comment_id>/reply',
         views.reply_comment, name='reply_comment'),
    path('<post_id>/<comment_id>/delete', views.delete_comment, name='delete_comment'),
]

squirrelfanbase/squirrelfanbase/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

squirrelfanbase/board/models.py
import datetime
import uuid
from django.db import models
from django.utils import timezone
from PIL import Image
from django.db.models.signals import pre_save, post_delete
from django.utils.text import slugify
from django.conf import settings
from urllib.parse import urlparse
from django.dispatch import receiver
from mptt.models import MPTTModel, TreeForeignKey


def get_thumb_image(instance, filename):
    file_path = 'post/{instance_id}/{title}-{filename}'.format(
        instance_id=str(instance.id), title=str(instance.title), filename=filename
    )
    return file_path


class Post(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=300, blank=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1, blank=False)
    image = models.ImageField(upload_to=get_thumb_image, height_field=None, width_field=None,
                              max_length=100, default=urlparse('i.stack.imgur.com/y9DpT.jpg'))
    created_at = models.DateTimeField(auto_now_add=True)
    last_edited_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, unique=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                   through='PostLikes',
                                   related_name='post_likes',
                                   related_query_name='post_like')

    def __str__(self):
        return self.title

    def was_submitted_recently(self):
        return self.created_at >= timezone.now() - datetime.timedelta(days=1)


class PostLikes(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE)
    liked_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user',
                                            'post'],
                                    name='unique_post_likes'),
        ]


@receiver(post_delete, sender=Post)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)


def pre_save_post_receiver(sender, instance, **kwags):
    if not instance.slug:
        instance.slug = slugify(
            instance.author.username + "-" + instance.title)


pre_save.connect(pre_save_post_receiver, sender=Post)


class Comment(MPTTModel):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1,
        blank=False, related_name="comments")
    parent = TreeForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE,
        related_name='children')
    reply_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='replyers'
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="comments")
    body = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                   through='CommentLikes',
                                   related_name='comment_likes',
                                   related_query_name='comment_like')

    class MPTTMeta:
        order_insertion_by = ['created_at']

    def __str__(self) -> str:
        return "<Comment: {} {}>".format(self.author.username,
                                         self.created_at.isoformat())

    def __repr__(self) -> str:
        return self.__str__()


class CommentLikes(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment,
                                on_delete=models.CASCADE)
    liked_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user',
                                            'comment'],
                                    name='unique_comment_likes'),
        ]

squirrelfanbase/board/forms.py
from django import forms
from board.models import Post, Comment
from mptt.forms import TreeNodeChoiceField

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'image']


class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description']


class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

squirrelfanbase/board/views.py
from board.forms import CreatePostForm, UpdatePostForm, CreateCommentForm
from .models import Post, Comment
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, HttpResponse


def index(request):
    latest_post_list = Post.objects.order_by('-created_at')[:5]
    return render(request, 'board/index.html', {'latest_post_list':
                                                latest_post_list})


def create_post(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(f"/board")

    form = CreatePostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        form = CreatePostForm()
        return HttpResponseRedirect(f"/board/{obj.id}")

    return render(request, "board/create_post.html", {})


def detail_view_post(request, id):
    post = Post.objects.get(id=id)
    comments = post.comments.filter()

    user_comment = None

    if request.method == 'POST':
        if not request.user.is_authenticated:
            return HttpResponseRedirect(f"/board/{post.id}")

        comment_form = CreateCommentForm(request.POST or None, request.FILES or None)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.author = request.user
            user_comment.save()
            return HttpResponseRedirect('/board/' + str(post.id))
    else:
        comment_form = CreateCommentForm()
    return render(request, "board/detail_view_post.html", {"post": post, "comments": user_comment, "comments": comments, "comment_form": comment_form, "user": request.user})


def update_view_post(request, id):
    obj = get_object_or_404(Post, id=id)

    if request.user != obj.author:
        return HttpResponse("You stink. That's not allowed")

    form = UpdatePostForm(request.POST or None, instance=obj)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(f"/board/{id}")

    return render(request, "board/update_view_post.html", {"form": form,
                                                           "data": obj})


def delete_post(request, id):
    obj = get_object_or_404(Post, id=id)

    if request.user != obj.author:
        return HttpResponse("You stink. That's not allowed")

    if request.method == "POST":
        obj.delete()
        return HttpResponseRedirect("/board")

    return render(request, "board/delete_post.html", {})

def delete_comment(request, post_id, comment_id):
    obj = get_object_or_404(Comment, id=comment_id)
    if request.user != obj.author:
        return HttpResponse("You shouldn't be here. Leave!")

    if request.method == "POST":
        obj.delete()
        return HttpResponseRedirect(f"/board/{obj.post.id}")
    return render(request, "comment/delete_comment.html")



def reply_comment(request, post_id, comment_id):
    post = get_object_or_404(Post, id=post_id)
    parent_comment = get_object_or_404(Comment, id=comment_id)

    if request.method == "POST":
        comment_form = CreateCommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = request.user
            new_comment.parent_id = parent_comment.get_root().id
            new_comment.reply_to = parent_comment.author

            new_comment.save()
            return HttpResponseRedirect(f"/board/{post.id}/#comment-{new_comment.id}")
        else:
            return HttpResponse("The form is incorrect, please fill it in again. ")

    elif request.method == "GET":
        comment_form = CreateCommentForm()
        context = {
            'comment_form': comment_form,
            'post': post,
            'parent_comment': parent_comment
        }
        return render(request, 'comment/reply_comment.html', context)
    else:
        return HttpResponse("Only GET/POST requests are accepted. ")

squirrelfanbase/board/templates/board/create_post.html
{% block content %}
<style type="text/css">
    .create-form {
        width: 100%;
        max-width: 100%;
        padding: 15px;
        margin: auto;
    }

    .submit-button {
        max-width: 200px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

                <!-- title -->
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required
                        autofocus>
                </div>

                <!-- Body -->
                <div class="form-group">
                    <label for="id_body">Description</label>
                    <textarea class="form-control" type="text" name="description" id="id_body"
                        placeholder="This post is about..." required></textarea>
                </div>

                <!-- Image -->
                <div class="form-group">
                    <label for="id_image">Image</label>
                    <input type="file" name="image" id="id_image" accept="image/*" required>
                </div>

                <!-- Submit Button -->
                <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
            </form>
        </div>
    </div>
</div>

{% endblock content%}

squirrelfanbase/board/templates/board/delete_post.html
<div class="main">
  <form method="POST">
    {% csrf_token %} Are you sure that you want to delete this item ?
    <input type="submit" value="Yes" />
    <a href="/board/">Cancel </a>
  </form>
</div>

squirrelfanbase/board/templates/board/detail_view_post.html
{% extends 'base.html' %}
{% load mptt_tags %}

{% block content %}
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{{ post.title }}</title>
  </head>
  <body>
    <div id="post">
      <a href="/board">Back to feed</a>
      <h1>{{ post.title }}</h1>
      <img
        src="{{ post.image.url }}"
        alt="{{ post.image.name }}"
        style="width: 40%"
      />
      <p>{{ post.description }}</p>
      {% csrf_token %}
      {% if user == post.author %}
        <button onclick="window.location.href='/board/{{ post.id }}/delete';">
          Delete
        </button>
        <button onclick="window.location.href='/board/{{ post.id }}/update';">
          Edit
        </button>
      {% endif %}
    </div>

    <div id="comments">
      <h1>Comments</h1>
      {% if user.is_authenticated %}
        <div style="display:block;">
          <form id="comment-form" method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn">Post</button>
          </form>
        </div>
      {% else %}
        <em><a href="/login" >Log in</a> to comment</em>
      {% endif %}
     
      <ul style="list-style-type: none;">
        {% recursetree comments %}
        {% with comment=node %}

        <div id="comment-{{ comment.id }}" style="outline-color: grey;outline-width: 2px;outline-style: solid;">
          <li style="list-style-type: none;">
            <p>By: {{ comment.author.username }} ({{ comment.created_at }})</p>
            {% if comment.reply_to %}
              <p>Replying to: {{ comment.reply_to.username }}</p>
            {% endif %}
            <p>"{{ comment.body|safe }}"</p>
            {% if user.is_authenticated %}
              <a href="/board/{{ post.id }}/{{ comment.id }}/reply">
                <button class="button">Reply</button>
              </a>
               {% if user.is_authenticated and user == comment.author %}
                  <div style="display:block;">
                    <button type="delete" class="btn" onclick="window.location.href='/board/{{ post.id }}/{{ comment.id }}/delete';">
                    Delete
                    </button> 
                  </div>
                {% endif %}
            {% else %}
              <a href="/login"><button class="button">Login to Reply</button></a>
            {% endif %}
            {% if not comment.is_leaf_node %}
              <ul class="children">
                {{ children }}
              </ul>
            {% endif %}
          </li>
        </div>

        {% endwith %}
        {% endrecursetree %}
      </ul>
    </div>
  </body>
{% endblock content %}

squirrelfanbase/board/templates/board/index.html
{% extends 'base.html' %}
{% block content %}
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>This is the main page</title>
  </head>
  <body>
    <h1>The Squirrel Fanbase</h1>
    <p>Have a look at our most recent submissions</p>

    {% if user.is_authenticated %}
      <div>
        Or
        <button onclick="window.location.href='/board/create';">Create</button>
        your own
      </div>
    {% else %}
      <div>
        Or <em><a href="/login" >Log in</a></em> to create your own
      </div>
    {% endif %}

    {% if latest_post_list %}
    <ul>
      {% for post in latest_post_list %}
      <li>
        <em>
          <a href="/board/{{ post.id }}/">{{ post.title }}</a>
        </em>
        <br />
        <img
          src="{{ post.image.url }}"
          alt="{{ post.image.name }}"
          style="width: 40%"
        />
        <p>{{ post.description }}</p>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No posts are available.</p>
    {% endif %}
  </body>
{% endblock content %}

squirrelfanbase/board/templates/board/update_view_post.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Editing {{ data.title }}</title>
  </head>
  <body>
    <form method="POST">
      {% csrf_token %}

      {{ form.as_p }}

      <input type="submit" value="Update" />
    </form>
  </body>
</html>